name: QA-Deploy

on:
  push:
    branches:
    - staging

jobs:
  qabuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 14.17.6
      uses: actions/setup-node@v1
      with:
        node-version: 14.17.6
    - name: npm install
      run: npm install
    - name: npm run build
      run: CI=false npm run build
      env:
        NODE_OPTIONS: --max_old_space_size=8192           
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting:htcapplicationtest
      env:
        PROJECT_ID: rameshtest-f25de     
    - name: Create SA key
       run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/gcloud.json
    - name: Deploy Cloud Functions
       run: export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json && npx firebase-tools deploy --only functions --json   