name: Deploy Cloud Functions
on:
  push:
    branches:
    - staging
jobs:
 qabuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.13.0
      uses: actions/setup-node@v1
      with:
        node-version: 12.13.0
    - name: npm install
      run: npm install
    - name: npm run build
      run: npm run build  
    - name: Create SA key
       run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/gcloud.json
    - name: Deploy Cloud Functions
       run: export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json && npx firebase-tools deploy --only functions --json